FROM python:3.12


WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install poetry 
RUN poetry install --no-root

COPY app.py ./

EXPOSE 8000

CMD ["poetry", "run", "streamlit", "run", "app.py", "--server.port=8000", "--server.address=0.0.0.0"]
