FROM python:3.12


WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install poetry 
RUN poetry install --no-root

COPY . PAKISTAN/dummy
EXPOSE 8000

RUN poetry run pip install streamlit

CMD ["poetry", "run", "uvicorn", "dummy.main:app", "--host", "0.0.0.0", "--port", "8000"]
